default_install_hook_types: ['pre-commit', 'prepare-commit-msg', 'commit-msg', 'pre-push']
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        stages: ['pre-commit']
      - id: pretty-format-json
        args: [--autofix]
        stages: ['pre-commit']
      - id: check-ast
        stages: ['pre-commit']
      - id: check-toml
        stages: ['pre-commit']
      - id: check-xml
        stages: ['pre-commit']
      - id: check-yaml
        stages: ['pre-commit']
      - id: debug-statements
        stages: ['pre-commit']
      - id: requirements-txt-fixer
        stages: ['pre-commit']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.1'
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|less|html|markdown|md|yaml|yml)$
        exclude: .*/templates/.*\.html$
        stages: ['pre-commit']
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
